# Generated by Django 3.2.8 on 2021-12-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=models.TextField(blank=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Website',
            field=models.URLField(blank=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='no_avatar.jpg', null=True, upload_to='User_profile_picture/'),
        ),
    ]
