# Generated by Django 3.2.8 on 2021-12-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20211223_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
