# Generated by Django 3.2.8 on 2021-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20211223_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='no_avatar.jpg', null=True, upload_to='User_profile_picture/'),
        ),
    ]
