# Generated by Django 3.2.8 on 2021-12-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='Website',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='connected_to',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='description',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='profile_pic',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
