# Generated by Django 3.2.8 on 2021-12-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0002_auto_20211223_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='Photo_Video',
            field=models.FileField(blank=True, null=True, upload_to='Alumni_Event/'),
        ),
        migrations.AddField(
            model_name='forum',
            name='Photo_Video',
            field=models.FileField(blank=True, null=True, upload_to='Forum_Files/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
