# Generated by Django 3.2.8 on 2022-01-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0003_auto_20211230_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Photo_Video',
            new_name='Video',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='Photo_Video',
        ),
        migrations.AddField(
            model_name='event',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='Alumni_Event/'),
        ),
        migrations.AddField(
            model_name='forum',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='Forum_Files/'),
        ),
    ]
