# Generated by Django 3.2.8 on 2022-02-28 12:55

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('sub_Title', models.CharField(max_length=250)),
                ('Video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
