# Generated by Django 3.2.8 on 2022-01-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zetechteam',
            name='Photo_Video',
        ),
        migrations.AddField(
            model_name='zetechteam',
            name='Photo',
            field=models.ImageField(null=True, upload_to='Home_page_photo/'),
        ),
        migrations.AddField(
            model_name='zetechteam',
            name='Video',
            field=models.FileField(null=True, upload_to='Home_page_photo/'),
        ),
    ]
