# Generated by Django 3.2.8 on 2022-01-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20220125_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zetechteam',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='Home_page_photo/'),
        ),
        migrations.AlterField(
            model_name='zetechteam',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='Home_page_photo/'),
        ),
    ]
