# Generated by Django 3.2.8 on 2021-12-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Users.user')),
                ('description', models.TextField(null=True)),
                ('Website', models.URLField()),
                ('phone', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='no_avatar.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
