# Generated by Django 3.2.8 on 2022-05-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='Whatsapp_Group_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
