# Generated by Django 3.2.8 on 2022-01-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Club', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Photo_Video',
        ),
        migrations.AddField(
            model_name='event',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='Club_event_file/'),
        ),
    ]
