# Generated by Django 3.2.8 on 2022-02-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-total_votes']},
        ),
    ]
